/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomDialog: typeof import('./src/components/CustomDialog.vue')['default']
    CustomDrawer: typeof import('./src/components/CustomDrawer.vue')['default']
    CustomDropdown: typeof import('./src/components/CustomDropdown.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    CustomNavigation: typeof import('./src/components/CustomNavigation.vue')['default']
    CustomOptionGroup: typeof import('./src/components/CustomOptionGroup.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiDelete: typeof import('~icons/mdi/delete')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    ItemsList: typeof import('./src/components/ItemsList.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    NewRole: typeof import('./src/components/NewRole.vue')['default']
    Role: typeof import('./src/components/Role.vue')['default']
    Roles: typeof import('./src/components/Roles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
